all: bottle-stopper-holder.stl bottle-stopper-topper.stl

bottle-stopper-holder.stl: bottle-stopper-holder.scad
	openscad -o $@ $^

bottle-stopper-topper.stl: bottle-stopper-topper.scad
	openscad -o $@ $^
